name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Assemble Library Release
      run: ./gradlew :folioreader:assembleRelease

    - name: Assemble Sample Release APK
      run: ./gradlew :sample:assembleRelease

    - name: Upload Library AAR
      uses: actions/upload-artifact@v4
      with:
        name: FolioReader-Android-AAR
        path: folioreader/build/outputs/aar/*.aar

    - name: Upload Sample APK
      uses: actions/upload-artifact@v4
      with:
        name: FolioReader-Sample-APK
        path: sample/build/outputs/apk/release/*.apk
